name: README Info Update

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: GitHub README Generator
    runs-on: ubuntu-latest
    steps:
      - uses: th3c0d3br34ker/github-readme-info@1.0.2
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          TIMEZONE: "Asia/Kolkata"
          SHOW_LINES_OF_CODE: "Flase"
          SHOW_PROFILE_VIEWS: "Flase"
          SHOW_DAILY_COMMIT: "Flase"
          SHOW_WEEKLY_COMMIT: "True"
          SHOW_LANGUAGE: "Flase"
          SHOW_TOTAL_CONTRIBUTIONS: "Flase"
